### ISSUE TITLE
[1.12-1.2.1] Steam Turbine only uses 4 mB/t of Steam?

### ISSUE THREAD

**Issue by Noodlebrain** [FerroO2000/Immersive-Tech#10]
This seems to be very little steam usage in exchange for 12,288 RF/t. Is this a bug, an oversight, or intended?

Additionally, is it also possible to make the steam usage of the Steam Turbine configurable, in order to help out pack makers?

**Comment by FerroO2000** [comment]
fixed. Now the file .jar is under processing on curse

**Comment by Noodlebrain** [comment]
While the default burn time of 1 bucket of steam has been changed to 50 ticks, resulting in 1000 mB / 50 ticks = 20 mB/t steam usage, it seems that the config value to alter burn time is not functional—setting burn time to lower values in config still results in 20 mB/t steam usage.
