### ISSUE TITLE
Wires keep breaking

### ISSUE THREAD

**Issue by LordRelentless** [FerroO2000/Immersive-Tech#103]
I've built a moving contraption by combining Immersive Engineering and Create using a Create addon mod that has an EF/IE compatible electric motor. The problem is when the contraption moves the wire and connector break. This is 1.19.2 current available version. Is it possible to get either a stretchy line set that doesn't break, or a reel system for extensible wires?

**Comment by LiskoSlayer63** [comment]
Your issue isn't related to Immersive Tech but to Immersive Engineering and Create. Also this mod has not been developed since MC 1.12.2.

I suggest you to open issue on [Immersive Engineering's Issue Tracker](https://github.com/BluSunrize/ImmersiveEngineering/issues)

**Comment by LordRelentless** [comment]
Oh, sorry, I must have mistaken this github for immersive engineering's github. My bad, and thanks for the help.
