### ISSUE TITLE
Distiller multiblock: broken texture and crash

### ISSUE THREAD

**Issue by Boundarybreaker** [FerroO2000/Immersive-Tech#12]
I'm trying out the most recent version of Immersive Tech today, and I just ran into a couple problems with the distillery. First off, the multiblock texture is completely broken.
![2017-08-23_23 04 19](https://user-images.githubusercontent.com/6722691/29651984-41964f96-8858-11e7-8e05-0a3f13d0bed5.png)

Second off, when I tried putting a Thermal Dynamics fluxduct on the power input (after I looked at the manual to see where on the multiblock's model the power input is), the game crashed. Here's the log for that.
[crash-2017-08-23_23.06.24-server.txt](https://github.com/FerroO2000/Immersive-Tech/files/1247897/crash-2017-08-23_23.06.24-server.txt)
Since the crash log says it's from the Immersive Engineering routines, I'm gonna report it to BluSunrize as well, but I want to put it here in case it's an issue with Immersive Tech.

**Comment by Boundarybreaker** [comment]
A contributor from the Immersive Engineering issue says that it's on Immersive Tech's side. Quote:

> This is on IT's side. The solar tower and possibly other MB's return null in getEnergyPos (as opposed to an empty array).

**Comment by FerroO2000** [comment]
For the texture, I have already answered here: https://github.com/FerroO2000/Immersive-Tech/issues/8

For the crash, I think I've found the problem (sideSolid in BlockITMultiblocks is the only thing IT multiblocks are different from IE)
