### ISSUE TITLE
What happened to the 1.11.2 version?

### ISSUE THREAD

**Issue by 63502** [FerroO2000/Immersive-Tech#21]
I may have missed something at some point, but what happened to the 1.11.2 version on curse or wherever it was? I have the 1.0 for 1.11.2 in my modded instance and it's functioning without crashing or anything(I haven't reached the point where I can use it though...). I don't see it anywhere for download anymore. 

I'm just curious.

**Comment by FerroO2000** [comment]
1.11 version didn't work fine so I have jumped in 1.12. The 1.11.2 will be re-added when v.1.4 of IT will be finished

**Comment by 63502** [comment]
Oh, ok. I look forward to playing with it when it's up for download again. I wish you luck with getting it working. 😄
