### ISSUE TITLE
Machines do not use "grey background"

### ISSUE THREAD

**Issue by Xiaminou** [FerroO2000/Immersive-Tech#28]
When opening the different machines UIs they do not have a grey background like the inventory does.

Minecraft: 1.12.2
Forge: 2537
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1464177/list.txt)

**Comment by Xiaminou** [comment]
Compare with this:
![2017-11-12_00 35 02](https://user-images.githubusercontent.com/8670392/32694704-0e22578a-c747-11e7-940e-915f95c3f8cc.png)

The machine's GUI is missing the "grey background" universally used by inventories and machines GUIs.

**Comment by FerroO2000** [comment]
Like immersive eng it uses a different texture for rhe inventory. It uses bricks for the inventory gui. Don't report fake issues

**Comment by Xiaminou** [comment]
I'm not talking about the central window's textures, I'm talking about the grey background behind the rest of the screen.
