### ISSUE TITLE
Machines do not auto-output

### ISSUE THREAD

**Issue by Xiaminou** [FerroO2000/Immersive-Tech#29]
This isn't a bug so much as it is an inconsistency, in Immersive Engineering machines such as the Fermenter and the Squeezer that produce fluid will auto-output them to connected pipes. Immersive Tech's machines do not.
If this is intentional just close this issue.

Minecraft: 1.12.2
Forge: 2537
Mods: [list.txt](https://github.com/CoFH/Feedback/files/1464177/list.txt)

**Comment by FerroO2000** [comment]
Can you post an image of this and gui?

**Comment by Xiaminou** [comment]
Oh right I took the screenshot but forgot to add it, there you go.

**Comment by FerroO2000** [comment]
The gui is ok

**Comment by Xiaminou** [comment]
Wait this is the auto-output bug, what does it have to do with GUI?

**Comment by FerroO2000** [comment]
The other issue you reported
