### ISSUE TITLE
Steam is not compatible with Thermal Expansion's Steam Dynamo

### ISSUE THREAD

**Issue by Xiaminou** [FerroO2000/Immersive-Tech#30]
I'm creating steam with Immersive Tech's Solar Tower and piping it into Steam Dynamo with the Turbine Augment. However those dynamos will not accept Steam.

![2017-11-11_23 31 41](https://user-images.githubusercontent.com/8670392/32694187-bd7eb204-c739-11e7-977f-ad7dda911cbd.png)

Here is the Thermal Expansion Issue: https://github.com/CoFH/Feedback/issues/628#issuecomment-343704897

**Comment by FerroO2000** [comment]
That bucket is of Thermal Foundation, not mine

**Comment by Xiaminou** [comment]
Read the Thermal Expansion Issue, KingLemming explains it.

**Comment by Xiaminou** [comment]
So, are you just not going to fix this issue or do you not trust KingLemming?

**Comment by FerroO2000** [comment]
I can fix it changing the id of my steam, but with another id it cannot be used by other machines like mekanism one

**Comment by KingLemming** [comment]
You don't have to fix the ID of your steam, you need to have your blocks produce the canonical steam for the world. You accomplish this by maintaining a fluid reference to FluidRegistry.getFluid("steam") and refreshing it on world load.

**Comment by Xiaminou** [comment]
Turns out it's not his Steam, it's Mekanism, I just tried with just Mekanism + TE and machines won't accept Steam anymore.

**Comment by Xiaminou** [comment]
Okay well I don't know anymore, seems to not work the first time I enter a world but if I reload this world it works, I don't know what to think and I don't know what's going on so I'll let you guys figure it out.

**Comment by FerroO2000** [comment]
Now is all ok? XD

**Comment by Xiaminou** [comment]
No, it's definitely broken in my modpack.

**Comment by Xiaminou** [comment]
So after further testing, Thermal Expansion's Steam Dynamo seems to be the only thing that does not accept steam in my modpack.

**Comment by Xiaminou** [comment]
https://github.com/aidancbrady/Mekanism/issues/4997
