### ISSUE TITLE
Crash on startup with IE 0.12-75 & IT 1.12-1.3.4

### ISSUE THREAD

**Issue by DeadSix27** [FerroO2000/Immersive-Tech#33]
MC: 1.12.2
Forge: 14.23.1.2578

Your addon crashes on startup, took me a while to narrow down...

As a modder, do you know better ways to debug crashes like this?
```
java.lang.NullPointerException: Initializing game
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)
	.....
```
Because it never mentions IE or your mod anywhere.

Stacktrace: https://gist.github.com/DeadSix27/c0b5c6e764ae4d19bbf91378ceffa6d5

**Comment by FerroO2000** [comment]
Try with immersiveengineering version 74

**Comment by DeadSix27** [comment]
@FerroO2000 Same crash, maybe newer forge causes it, they probably changed something.
