### ISSUE TITLE
better alternator output / compatability.

### ISSUE THREAD

**Issue by Mementh** [FerroO2000/Immersive-Tech#34]
the alternator seems to only ouput to IE power systems unlike the Diesel generator which has a universal output. 

The alternator has no specified output amount, it would be nice to have the manual show what it can be.

**Comment by Vyraal1** [comment]
Also want to second on supporting RF / FE compatability for the Alternator. It won't connect to anything except IE Connectors.

**Comment by anpilley** [comment]
In addition, if you're going to stick to IE connectors, perhaps adding a mega-volt class of connector/wire so more can be drawn from the alternator? currently with 6 HV connectors, the most you can pull from the alternator is 24,576rf/t, but it seems like the alternator can generate way more than that per tick. A quick glance suggests that it can generate 62,914RF/t, but there's just no way to draw that much power from it.

**Comment by anpilley** [comment]
It looks like IE Tech is only checking for IE's interface IFluxReceiver, and not checking Forge's generalized CapabilityEnergy.ENERGY for attached tileEntities it can transmit to. IE's diesel generator tries both when outputting power.

**Comment by Mementh** [comment]
at least we know why its not working.. hopefully its fixed in a patch

**Comment by MrBirk** [comment]
Would love to see this be implemented across the board for immersive tech. I have been loving the the mod and all the additional structures it adds.

**Comment by FerroO2000** [comment]
added more compatibilities
