### ISSUE TITLE
Solar tower rendering issue

### ISSUE THREAD

**Issue by thehobojoe** [FerroO2000/Immersive-Tech#36]
Often the solar tower fails to render correctly. It's triggered by many different things, most commonly simply opening the engineers manual.

![2018-02-11_02 22 55](https://user-images.githubusercontent.com/3493638/36071374-dba2cc30-0ed2-11e8-84c1-0584f3528eb8.png)

**Comment by DreadBoy** [comment]
I'm getting same glitch but my world also crashes. Here's a crashlog:

https://gist.github.com/DreadBoy/250a70c5bdc6bb8540945f868dadd2b0
