### ISSUE TITLE
[1.12.2] Steam Turbine steam usage is enormous

### ISSUE THREAD

**Issue by LiskoSlayer63** [FerroO2000/Immersive-Tech#37]
Even three boilers can't keep up with Steam Turbines steam consumption and the config doesn't do anything. I tried to change the burnTimeModifier to 0 and it _still_ uses the steam more than I can produce. Is this a bug?

**Comment by Koltanas** [comment]
If you reduce the burn time you increase the usage of steam. But i have to say that the Turbine indeed uses to much steam on standard settings. A burn time of 75 actually is better imho.

**Comment by LiskoSlayer63** [comment]
It says that it calculates the mB/t usage like this: `(1000 / steamBurnTime) * steamTurbine_burnTimeModifier`

The `steamTurbine_burnTimeModifier` is set to 3 by default but if I change it to 1, does it really _increase_ the usage?

**Comment by Koltanas** [comment]
OK, I mixed uo the Modifier with the burn time. Increase that one from 50 to 75 or 100 and you should be good to go.

**Comment by BigKid1973** [comment]
There seems to be something off... I tried to change
I:steamTurbine_burnTimeModifier=5

I also tried to add:
I:steamTurbine_burnTime=100
I:solarTower_steamDistWater=1000
I:solarTower_steamWater=500

The turbine just seems to suck everythin the tower has... No matter what...

**Comment by xdestviz** [comment]
Same problem here, the config file doesn't do anything at all. Tried changing the burnTimeModifier to 10000, nothing changed.

**Comment by LiskoSlayer63** [comment]
If I recall correctly that bug was caused by the code not reading the `steamTurbine_burnTimeModifier` variable at all. 

This mod is long dead, please switch to the [Immersive Technology](https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology) by MCT. It also has some cool additions and is actively maintained.
