### ISSUE TITLE
[1.12.2] Crash

### ISSUE THREAD

**Issue by Vyraal1** [FerroO2000/Immersive-Tech#38]
https://hastebin.com/enezilenun.sql

Was exploring the worldgen, I guess something went wrong back in my home base as it was unloading?

**Comment by Whiskey-Sunshine** [comment]
https://pastebin.com/g6kq3ejr

Currently having the same issue, the boiler seems to want to keep ticking even while unloaded, resulting in trying to tick a tile entity that doesn't exist in loaded memory. I noticed that it only happens to me when the area is unloaded, either when walking away and having chunks unload behind me (usually immediate) or teleporting away, both through nether or by more direct means such as the /tp command (May take some time between unloading and breaking).

**Comment by LiskoSlayer63** [comment]
@Whiskey-Sunshine What forge version are you using? 

This is weird, either my server does never unload those chunks or there's something changed in forge. I'll try to look at it.

**Comment by Whiskey-Sunshine** [comment]
@LiskoSlayer63 1.12.2-14.23.1.2560 server and client, happens on SMP over here. Will check if updating forge will fix.

**Comment by LiskoSlayer63** [comment]
I'll investigate it more when I get back to home, can't actually do anything with this laptop.

**Comment by Whiskey-Sunshine** [comment]
Went ahead and copied the server world to single player and attempted to recreate it in both forge version 14.23.1.2560 and 14.23.2.2611, was unable to recreate the issue in SSP even with roughly half an hour of continuous moving in and out of loading range on each version. Repeatable on SMP in both versions, though it tends to be finicky if it wants to or not. Seems to happen most often when walking away from the loaded chunks within the same region, but may spontaneously do so at any time when teleporting into a new region, sometimes 15-20 minutes after the fact.

**Comment by LiskoSlayer63** [comment]
Thanks for the information. I'll report here when I have time. Can you check that if it's still happening with Immersive Engineering 0.12-77 and [Immersive Tech 1.3.5](https://github.com/FerroO2000/Immersive-Tech/releases/tag/1.3.5)?

**Comment by Whiskey-Sunshine** [comment]
Will do so tomorrow, server owner went to sleep so I'm stuck on it for now. Will add now, forgot to mention, this is Immersive Engineering 0.12-77, Immersive Petroleum 1.1.7, and Immersive Tech 1.3.4. Thank you for reminding me.

**Comment by Whiskey-Sunshine** [comment]
Apologies for taking so long. Updated to IT 1.3.5, causes immediate crash during load. Not sure what's going on this time, myself.

Most recent report: https://pastebin.com/LAsigyGJ

**Comment by FerroO2000** [comment]
You are using immersive engineering 76. Try with 77

**Comment by Whiskey-Sunshine** [comment]
You know, I did download that update but I suppose I didn't actually add it yet. Color me stupid. Thanks!

**Comment by FerroO2000** [comment]
;)
