### ISSUE TITLE
[1.12] Crash with latest Immersive Engineering

### ISSUE THREAD

**Issue by raltus** [FerroO2000/Immersive-Tech#39]
I updated to the latest Immersive Engineering 0.12 - 77, and it crashed. After trying to update forge and having the same thing happen I rolled back one version and it loads fine. I assume it's something that changed in the latest version that's causing a incomparability.

Crash report
https://gist.github.com/raltus/403620b1da1397cabbc5bfc560904fc9.

**Comment by LiskoSlayer63** [comment]
This is actual fixed already but it hasn't been uploaded to CurseForge yet.

**Comment by bonnedav** [comment]
where can i get a build?

**Comment by raltus** [comment]
Thanks, I'll hold off on updating Immersive Engineering until it is then.

**Comment by LiskoSlayer63** [comment]
@raltus You can download the binary [here](https://github.com/FerroO2000/Immersive-Tech/releases/tag/1.3.5).
