### ISSUE TITLE
[1.11][Bug] Multiblock missing textures.

### ISSUE THREAD

**Issue by Mike-T4** [FerroO2000/Immersive-Tech#4]
In the 1.11 versions, all Multiblock structures appear to have missing textures.
The same goes for their textures.

![gmod](https://user-images.githubusercontent.com/12882669/29495305-f374ad8c-85bc-11e7-87ce-94a6a50625f4.png)

Only Immersive Engineering and Immersive Tech are installed. Forge version: 2386.

Another minor bug that probably doesn't warrant it's own issue: The Solar Tower entry tooltip claims you need a Block of Steel, but you actually need a Block of Silver.

**Comment by FerroO2000** [comment]
I need more time to update to 1.11. Thanks for your message
