### ISSUE TITLE
Boiler crash in SMP when unloading chunks containing boiler

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [FerroO2000/Immersive-Tech#42]
https://pastebin.com/zYEgWpCC

IE .12-77, IT 1.3.5, Forge 14.23.1.2560, JRE 8u162

Seems to be the same issue as #38 though not as severe as before. Can log back in afterwards without repeatedly crashing as before in IT 1.3.4. Still unable to recreate in SSP.

**Comment by LiskoSlayer63** [comment]
This is weird, I'm using exactly the same versions on my server without any crashes. I'll try to investigate this.

**Comment by artdude543** [comment]
@LiskoSlayer63 this is an issue with a large group of our users. Can this be looked into, please? And/Or this issue being re-opened for the purpose that it's not fixed. Thanks.

**Comment by LiskoSlayer63** [comment]
@artdude543 Reopened since the issue still persists. Do you know a reliable way to reproduce this?

**Comment by artdude543** [comment]
I have not progressed enough in my world to get this issue but if you take a gander at the linked issue; you can ask the users there which are having the issues. But I've seen the crash log a lot in the issue tracker for SevTech.

**Comment by artdude543** [comment]
Question; what is the time frame for an update to be published to CF?

**Comment by FerroO2000** [comment]
Today will be approved the update with the fix
