### ISSUE TITLE
broken ore dictionary registration

### ISSUE THREAD

**Issue by ninjamask** [FerroO2000/Immersive-Tech#43]
10:22:48 | FML | main | warn | ****************************************
-- | -- | -- | -- | --
10:22:48 | FML | main | warn | * A broken ore dictionary registration with name dustSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:110)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
10:22:48 | FML | main | warn | *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
10:22:48 | FML | main | warn | ****************************************
10:22:48 | FML | main | warn | ****************************************
10:22:48 | FML | main | warn | * A broken ore dictionary registration with name itemSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:111)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
10:22:48 | FML | main | warn | *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
10:22:48 | FML | main | warn | ****************************************
10:22:48 | FML | main | warn | ****************************************
10:22:48 | FML | main | warn | * A broken ore dictionary registration with name foodSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry. TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
10:22:48 | FML | main | warn | *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:112)
10:22:48 | FML | main | warn | *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
10:22:48 | FML | main | warn | *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
10:22:48 | FML | main | warn | ****************************************

**Comment by LiskoSlayer63** [comment]
What versions are you using? And what other mods you have installed? Also can you tell that if this happened on singleplayer or multiplayer?

**Comment by ninjamask** [comment]
im playing [FS Lost Souls v-1.0.3.9-B3](https://www.curseforge.com/minecraft/modpacks/forever-stranded-lost-souls) and checking the debug console.

**Comment by LiskoSlayer63** [comment]
I was busy and forgot this, sorry. I'll fix this during the weekend.
