### ISSUE TITLE
Broken OreDictionary

### ISSUE THREAD

**Issue by ggblbl** [FerroO2000/Immersive-Tech#44]
I got an error on my server during startup and Forge told me to report it, so here it is:

> `17:19:59 [WARNING] [FML]: A mod has attempted to assign Block Block{null} to the Fluid 'steam' but this Fluid has already been linked to the Block Block{advgenerators:steam}. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
17:19:59 [WARNING] [FML]: ****************************************
17:19:59 [WARNING] [FML]: * A broken ore dictionary registration with name dustSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
17:19:59 TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:110)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
17:19:59 [WARNING] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
17:19:59 [WARNING] [FML]: ****************************************
17:19:59 [WARNING] [FML]: ****************************************
17:19:59 [WARNING] [FML]: * A broken ore dictionary registration with name itemSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
17:19:59 TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:111)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
17:19:59 [WARNING] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
17:19:59 [WARNING] [FML]: ****************************************
17:19:59 [WARNING] [FML]: ****************************************
17:19:59 [WARNING] [FML]: * A broken ore dictionary registration with name foodSalt has occurred. It adds an item (type: class ferro2000.immersivetech.common.items.ItemITBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
17:19:59 TO USERS: YES this is a BUG in the mod Immersive Tech report it to them!
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:656)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
17:19:59 [WARNING] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:626)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.common.ITContent.preInit(ITContent.java:112)
17:19:59 [WARNING] [FML]: *  at ferro2000.immersivetech.ImmersiveTech.preInit(ImmersiveTech.java:43)
17:19:59 [WARNING] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
17:19:59 [WARNING] [FML]: ****************************************`

**Comment by dshadowwolf** [comment]
OreDictionary registration, in 1.12, can happen no earlier than the "RegistryEvent.Register<Item>" event handler. It appears that ImmersiveTech has not changed this behavior from older versions.
