### ISSUE TITLE
multiblocks dont seem to work any more with the newest immersive engineering version

### ISSUE THREAD

**Issue by Wotzinator** [FerroO2000/Immersive-Tech#48]
since immersive engineering had to deal with some multiblock problem everything should be fixed in the main mod but i realized that the multiblocks from this mod dont seem to work properly anymore .if you right-click a multiblock structure the gui wont open and the structure seem to have lost there functionaliti.

**Comment by FerroO2000** [comment]
IE and IT versions?

**Comment by Wotzinator** [comment]
IE:0.12-80
IT:1.3.6

**Comment by justinrusso** [comment]
IE did change something and caused GUIs to break on all the addon mods. See IP as well: https://github.com/Flaxbeard/ImmersivePetroleum/issues/106

**Comment by warlordjones** [comment]
The maven should be back up and running

**Comment by Wotzinator** [comment]
as i know flaxbeard already fixed that issue

**Comment by justinrusso** [comment]
Looks like IE is back up on the CI now https://ci.blamejared.com/job/Immersive%20Engineering/

**Comment by FerroO2000** [comment]
Fixed
