### ISSUE TITLE
Feature request salt oredictionary

### ISSUE THREAD

**Issue by Staegrin** [FerroO2000/Immersive-Tech#5]
Might I suggest adding the oredictionary entries for salt to the salt produced by the distiller. Making it compattible with the other mods that use salt like Mekanism and Pam's harvestcraft...
itemSalt
dustSalt
foodSalt

**Comment by aetherknight** [comment]
In addition to the 3 slats listed above, Animania also adds its own version of salt to `listAllSalt`, and `salt` in the oredictionary.

**Comment by LiskoSlayer63** [comment]
I made a mod for this, it's called [Immersive Tech OreDictionary](https://minecraft.curseforge.com/projects/immersive-tech-oredictionary). It adds the salt to OreDictionary with `itemSalt`, `foodSalt` & `dustSalt`.

**Comment by FerroO2000** [comment]
Nice job @LiskoSlayer63. I was thinking to remove salt because it was completely useless (it was a part of the mod that i had dumped).

Is there a possibility to include your mod into IT?

**Comment by LiskoSlayer63** [comment]
Yes there is. Do you want to add it or do I make a commit/pull request?

**Comment by FerroO2000** [comment]
Commit

**Comment by LiskoSlayer63** [comment]
@FerroO2000 I opened a pull request.
