### ISSUE TITLE
Client crash when forming an advanced coke oven.

### ISSUE THREAD

**Issue by ProsperCraft** [FerroO2000/Immersive-Tech#52]
https://pastebin.com/RHp7wXAA

And another user here-

https://gist.github.com/ProsperCraft/5900e72ae543f59326052b4601d5859b

Server environment-
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3025
    Minecraft Forge: 14.23.3.2655

Modpack -
https://minecraft.curseforge.com/projects/towncraft

**Comment by FerroO2000** [comment]
Because it isn't done yet, dont't build it. There is only the multiblock instance registered because i thought that nobody would have built the structure

**Comment by ProsperCraft** [comment]
They say they got the idea to build it from the wiki.

**Comment by ProsperCraft** [comment]
Also it is in the manual.

**Comment by F9Alejandro** [comment]
Please mark the block as WIP (Lore) and/or mark it in the manual, people are less likely to build it if they know it is likely to crash.

**Comment by Keridos** [comment]
This should really be fixed, either by not registering the multiblock, but having the blocks inside, having it in the manual and not marked as WIP or anything will cause people to try to build it.

**Comment by FerroO2000** [comment]
Try 1.3.8 version
