### ISSUE TITLE
[Crash-1.12.2]Crash in the games

### ISSUE THREAD

**Issue by Anguriaboy** [FerroO2000/Immersive-Tech#57]
[crash-2018-05-11_21.16.57-client.txt](https://github.com/FerroO2000/Immersive-Tech/files/1996382/crash-2018-05-11_21.16.57-client.txt)

Using immersivetech-1.12-1.3.8
Forge 2655

That issue make Client collapse

**Comment by 0uti** [comment]
same here, but with WAILA instead of TheOneProbe.

https://pastebin.com/WRXDzLr0

**Comment by artdude543** [comment]
Same issue here with SevTech instances: https://github.com/DarkPacks/SevTech-Ages/issues/2442 @ferro2000 can this be looked into? Causing a lot of issues with SevTech users 😭

**Comment by FerroO2000** [comment]
I will fix it as soon as possible

**Comment by FerroO2000** [comment]
I cannot reproduce the crash. It seems to be all ok

**Comment by artdude543** [comment]
It's an issue as I've had over 40 reports now. And a few worlds broken from the ticking exception thrown from the null. This is a mod cross over issue tho but can a null check be thrown in with logging so we can track the cause for it.

**Comment by FerroO2000** [comment]
@artdude543 are you able to replicate the crash?

**Comment by artdude543** [comment]
I can not personally no, And I've tried all the silly things a typical player would do. My only guess on this could be odd loading issues in a world when it forms/breaks. But regardless the error is caused when your trying to check a stack is not empty. This should be null-checked anyway to prevent issues as a stack could be null at any time/point.

From gandering at the code it would more likely been null from this check: 
https://github.com/FerroO2000/Immersive-Tech/blob/8ea495b8ccd01e9440d7f3ed19eef04cb9c309d6/src/main/java/ferro2000/immersivetech/common/blocks/BlockITMultiblock.java#L70-L72

Which suggests to me it's an odd issue with the multiblock.

**Comment by FerroO2000** [comment]
The strange thing is that the class is a copy of the IE one

**Comment by artdude543** [comment]
Yeah that's what I was comparing over too. If anything this is more of a rare case but as I've had way too many reports I can't really call it a rare case bug.

**Comment by artdude543** [comment]
@ferro2000 we got another report with the same crashing issue the OP gave some more details https://github.com/DarkPacks/SevTech-Ages/issues/2574

**Comment by FerroO2000** [comment]
The new version should fix this problem.
https://github.com/FerroO2000/Immersive-Tech/releases/tag/1.3.9

**Comment by FerroO2000** [comment]
finally fixed
