### ISSUE TITLE
[1.12.1] Mark as compatible

### ISSUE THREAD

**Issue by angelnc1989** [FerroO2000/Immersive-Tech#6]
I just saw you released a 1.12 version. Could you mark it as compatible for 1.12.1?

**Comment by Alaberti** [comment]
It's not quite compatible with 1.12.1 yet from what I saw - it loads, but only three items and no blocks are visible in JEI.

**Comment by angelnc1989** [comment]
Are there more items than salt? Salt, Distilled Water and Steam show up in JEI.
The only thing that seemed to be broken on first glance were the GUI textures.

**Comment by FerroO2000** [comment]
@Alaberti 
The mod adds only 2 fluids and 1 item at the moment. The rest of the contents are multiblocks

**Comment by Alaberti** [comment]
@FerroO2000

Thanks for clarifying

**Comment by FerroO2000** [comment]
done
