### ISSUE TITLE
Snow layers on solar reflectors block the sun.

### ISSUE THREAD

**Issue by cheesealmighty** [FerroO2000/Immersive-Tech#61]
Snow layers on solar reflectors  seems to be blocking the sun. While one might suggest I shouldn't even be able to use solar power in a wintery biome (or in winter season, because mods), fair enough, but when this could be prevented with a simple torch placement, the specifics are lost. 

I would humbly suggest making the mirror's top/sun checking part heat emitting, so the snow melts when it falls on it.

**Comment by FerroO2000** [comment]
What's the real problem?

**Comment by cheesealmighty** [comment]
Oh, it's simply an issue of aesthetics. "Immersive   ............." series always seemed to be centered about things looking, uh, pretty? But in the end, obviously this is a design decision.

**Comment by FerroO2000** [comment]
Sorry, but it is a design decision
