### ISSUE TITLE
Solar Tower seems not working

### ISSUE THREAD

**Issue by mashumarodesu** [FerroO2000/Immersive-Tech#72]
I built the Solar Tower and 4 Solar Reflectors right next to it but it still says no reflector available (4 squares not glow)
I'm at IT 1.3.10 and I also tried 1.3.9 and 1.3.8 but it's still the same

**Comment by FerroO2000** [comment]
you have to build the reflectors in order to fit the exagon of the tower. In the manual is also wrote the min and max distance that must be between the tower and the reflectors
