### ISSUE TITLE
Steam Turbine Steam Consumption vs. Alternator Power Output

### ISSUE THREAD

**Issue by voidsong-dragonfly** [FerroO2000/Immersive-Tech#77]
The steam turbine consumes 50 mb/t steam to produce, as stated in the config, 6144 rad/s at 8192 Nm. This, with the power equation 
`((speed*torque)/800)`
from the config, should produce 62914 RF/t. The alternator, however, can only output 4096 RF/t per connector, as it should to mesh with IE HV cabling. This leads to the alternator outperforming its max output by a ratio of 2.5, and only outputting 24,576 RF/t. I suggest lowering the max consumption of the steam turbine to 20 mb/t, and lowering the max torque to 2048 Nm, and then lowering power multiplier to be 512 W = 1 RF/t, similar to the ratio Reika calculated for W to Rf/t. When you run the calculation with these values
`((6144*2048)/512)`
You get 24,576 RF/t, the max output for the alternator, while consuming 2.5 times less steam and producing 2.5 times less power. As a bonus, the calculation is more realistic. This leaves only the boilers to be rebalanced, but you could already run a steam turbine off of two boilers anyway, so the balance would not change.

**Comment by voidsong-dragonfly** [comment]
As a side note, if you set the
`# The max of Flux that the Alternator can output per each energy device connected
        I:alternator_RfPerTick=4096`
part of the config to something like 32768, the alternator, which is now not receiving enough power to keep up with six outputs, will output 6 times `I:alternator_RfPerTick` modifier.
This means that, with 32768 as the modifier you are producing 196608 Rf/t.

**Comment by ranger135xp** [comment]
How would you increase the amount of steam needed to reach maximum power?
I need to do this to prevent #51 which allows Thermal Expansion Dynamos to make 40 mb/t of steam and run this at max power from 1 charcoal.

**Comment by voidsong-dragonfly** [comment]
There is a config with something like 
‘steamTurbineMult=5’
This is the number, in 10s of mb/t, that the steam turbine produces. Raise that to something like 16. That *should* solve your problem.

**Comment by Silfryi** [comment]
There is a config with something like 
‘steamTurbineMult=5’
This is the number, in 10s of mb/t, that the steam turbine produces. Raise that to something like 16. That *should* solve your problem.

**Comment by ranger135xp** [comment]
Following the math in the config, ((1000 / steamBurnTime) / 2) * steamTurbine_burnTimeModifier mb/t [steamBurnTime = 50], The config let's you adjust steamTurbine_burnTimeModifier.
If steamBurnTime = 50 and steamTurbine_burnTimeModifier=5 like in the default config, then it equals 50mb/t for max.
I changed this to 500 which should result in needing 5000mb/t for max output.

Would you agree?

**Comment by voidsong-dragonfly** [comment]
That should do it.

**Comment by spylor** [comment]
How much steam does a solar tower with 4 reflectors produce during day time per tick?

**Comment by spylor** [comment]
Or maybe this is a better question: How many ticks does it take to convert a bucket into steam? Does the amount of reflectors reduce this time or does it increase the amount of buckets converted?

**Comment by spylor** [comment]
What I'm trying to do is: I want 4 solar towers to be needed to power 1 turbine at full speed. And I want boilers to need 2 times as much fuel as diesel generators for the same output in RF.

**Comment by ranger135xp** [comment]
From what we found,  I:solarTower_timeModifier doesn't effect the amount of steam output by the solar boilers. It also does not have an equation in the comment about this value explaining the outcome.

Unfortunately, the only solution is to prevent other mods from inputting steam into the turbine.
It's rather lame and unfortunate that this mod has such a low threshold for steam required to make such a high amount of RF and the only option seems to be nerfing the RF output.
Especially when other mods that have been around longer have set somewhat of a standard of 1000's of Mb/t of steam to get this kind RF output.

Now my current solution is to remove the recipe for the Thermal Expansion augment that allows the steam dynamo to output steam instead of RF.

**Comment by msgerbs** [comment]
I hope the author looks at this soon. Another possible alternative might be to allow multiple alternators to stack one after the other, with each one taking an equal share of the generated electricity. That would be pretty cool. Either way the numbers for these generators need some looking at.

**Comment by voidsong-dragonfly** [comment]
Closed because [https://github.com/tgstyle/MCT-Immersive-Technology/](https://github.com/tgstyle/MCT-Immersive-Technology/) fixes this.

**Comment by ranger135xp** [comment]
good! I'm replacing immersive tech with that right now.
