### ISSUE TITLE
[1.12] Missing GUI textures

### ISSUE THREAD

**Issue by NillerMedDild** [FerroO2000/Immersive-Tech#8]
Hey!

The Solar Tower's GUI has the broken-texture-texture:

![billede](https://user-images.githubusercontent.com/21295394/29565253-7a4969fe-8745-11e7-9724-1c5d0916cc5f.png)
![billede](https://user-images.githubusercontent.com/21295394/29565259-7d8db39a-8745-11e7-9da8-60ceb9999c1c.png)

And the same goes for the Distiller:
![billede](https://user-images.githubusercontent.com/21295394/29565532-a5584b5a-8746-11e7-8740-02bc63dedc7e.png)
The multiblock texture is a bit off aswell:
![billede](https://user-images.githubusercontent.com/21295394/29565536-a9f84430-8746-11e7-9c46-716299f67fa5.png)

Minecraft 1.12
Forge 1.12-14.21.1.2443
immersivetech-1.12-1.2
ImmersiveEngineering-0.12-70

**Comment by NillerMedDild** [comment]
The multiblock texture of the Distiller still looks like the last image, with the new version. 
The GUIs look great though!

**Comment by FerroO2000** [comment]
I used C4d for the models, and its mirror tool inverts the face(inside-outside). Not mirrored Distiller works fine. Now I am working on new contents. The mirrored Distiller texture will be fixed with the next version.
I'm sorry

**Comment by NillerMedDild** [comment]
No worries :)

The other machines look really great, and I think the outputs of the machines are spot on, in particular the Steam Turbine's energy output - Great work.

**Comment by FerroO2000** [comment]
Thanks
