### ISSUE TITLE
[1.12] Missing config

### ISSUE THREAD

**Issue by NillerMedDild** [FerroO2000/Immersive-Tech#9]
Hey!

The config file generated looks like this, I'm guessing it's not intentional.

![billede](https://user-images.githubusercontent.com/21295394/29565427-2bfdb182-8746-11e7-8113-3ab3108d070b.png)

Minecraft 1.12
Forge 1.12-14.21.1.2443
immersivetech-1.12-1.2
ImmersiveEngineering-0.12-70

**Comment by FerroO2000** [comment]
thanks for reporting, now config and texture bugs are fixed

**Comment by NillerMedDild** [comment]
Thank you :D
