### ISSUE TITLE
Steam turbine DOSE NOT WORK AT ALL 

### ISSUE THREAD

**Issue by ArtemK216** [FerroO2000/Immersive-Tech#90]
I have a problem where I have set up a system:
I have a boiler boil water into steam which then goes to the tank and out of the tank into the turbine. I have checked 100 times I know I set everything up correctly (alternator and turbine facing the right way and such)
So I have full steam tank connected to the turbine but nothing happens no matter if I turn on the restore or not whether it would be to drain the steam or power the turbine NOTHING.
I have tried everything please help ?! 

![2019-07-05_13 04 00](https://user-images.githubusercontent.com/52578958/60736677-c50bc500-9f25-11e9-8e27-e695a86bfa21.png)
![2019-07-05_13 04 07](https://user-images.githubusercontent.com/52578958/60736685-d05ef080-9f25-11e9-9a01-ffb0fee4719e.png)
![2019-07-05_13 04 20](https://user-images.githubusercontent.com/52578958/60736692-d2c14a80-9f25-11e9-923b-eaa21c23ccdf.png)

**Comment by LiskoSlayer63** [comment]
These might be stupid questions but I need to confirm. Are the turbines rotating at all? If not, is there levers on the bottom block of the tanks to let them output steam? I'm not also sure if the alternator can output straight to the capacitor or does it need a connector and a wire.

**Comment by ArtemK216** [comment]
"These might be stupid questions but I need to confirm. Are the turbines rotating at all? If not, is there levers on the bottom block of the tanks to let them output steam? I'm not also sure if the alternator can output straight to the capacitor or does it need a connector and a wire."

1 I have malisis switch as the lever and it works fine 
2 Yes the Alternator can output straight to capacitors

I forgot to mention that when you just finish the multiblock and you input steam the turbine spins for 2 seconds then stops, some times it doesn't spin at all and just drains steam and stops

**Comment by ArtemK216** [comment]
I understood my mistake, all I needed is to hit the capacitors with the hammer on the side to make input.
When I saw youtube videos I say all people place the capacitors just adjacent and it worked (without hitting to make input) I guess different versions work differently

**Comment by LiskoSlayer63** [comment]
Good that you figured it out and got it working!
